# Generated by Django 5.1 on 2025-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='services',
            name='highlight',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='highlights',
            name='title',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='home',
            name='career',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='home',
            name='first_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='home',
            name='greeting',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='last_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=254),
        ),
    ]
