# Generated by Django 5.1 on 2025-05-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_services_options_services_highlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords (e.g., Python,Cloud,ML)', max_length=512),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(default='Personal Project', max_length=254),
        ),
        migrations.AddField(
            model_name='projects',
            name='tagline',
            field=models.TextField(blank=True, default=''),
        ),
    ]
